using System;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using Grasshopper;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Data;

namespace SampleBuilder
{
    /// <summary>
    /// Writes the component reference of the documentation site (Docusaurus): one folder per toolbar panel, one page per
    /// component with its inputs and outputs, a page for the parameters, and the 24×24 icons. Generated from the loaded
    /// plugin, so the pages match the components.
    /// </summary>
    internal static class Docs
    {
        /// <summary>Writes the pages into <paramref name="docsDir"/> and the icons into <paramref name="iconDir"/> (served at <paramref name="iconUrl"/>).</summary>
        public static int Write(string docsDir, string iconDir, string iconUrl)
        {
            var proxies = Instances.ComponentServer.ObjectProxies.Where(p => p.Desc.Category == "IfcHopper" && !p.Obsolete).ToList();
            if (Directory.Exists(docsDir)) Directory.Delete(docsDir, true);
            Directory.CreateDirectory(docsDir);
            Directory.CreateDirectory(iconDir);
            WriteCategory(docsDir, "Components", 3, "Every IfcHopper component with its inputs and outputs, by toolbar panel.");

            var pages = 0;
            foreach (var panel in proxies.GroupBy(p => p.Desc.SubCategory).OrderBy(g => g.Key))
            {
                var (position, label) = Panel(panel.Key);
                var dir = Path.Combine(docsDir, Slug(label));
                Directory.CreateDirectory(dir);
                WriteCategory(dir, label, position, $"Components of the {label} panel.");

                var components = panel.Select(p => (proxy: p, component: p.CreateInstance() as IGH_Component)).Where(c => c.component != null)
                    .OrderBy(c => (int)c.proxy.Exposure).ThenBy(c => c.proxy.Desc.Name).ToList();
                for (var i = 0; i < components.Count; i++)
                {
                    var (proxy, component) = components[i];
                    var slug = Slug(proxy.Desc.Name);
                    proxy.Icon?.Save(Path.Combine(iconDir, slug + ".png"), ImageFormat.Png);
                    File.WriteAllText(Path.Combine(dir, slug + ".md"), Page(component, label, i + 1, proxy.Icon == null ? null : $"{iconUrl}/{slug}.png"));
                    pages++;
                }

                var parameters = panel.Where(p => p.Exposure != GH_Exposure.hidden && p.CreateInstance() is IGH_Param).ToList();
                if (parameters.Count > 0)
                {
                    File.WriteAllText(Path.Combine(dir, "parameters.md"), ParamsPage(parameters, label, iconDir, iconUrl));
                    pages++;
                }
            }
            Console.WriteLine($"Wrote {pages} pages in {docsDir}.");
            return 0;
        }

        private static string Page(IGH_Component component, string panel, int position, string icon)
        {
            var text = new StringBuilder();
            text.AppendLine("---");
            text.AppendLine($"sidebar_position: {position}");
            text.AppendLine($"title: {component.Name}");
            text.AppendLine($"sidebar_label: {component.Name}");
            text.AppendLine("---");
            text.AppendLine();
            text.AppendLine("{/* Generated by tools/SampleBuilder --docs from the IfcHopper components; do not edit by hand. */}");
            text.AppendLine();
            if (icon != null) text.AppendLine($"![{component.Name}]({icon}) ");
            text.AppendLine($"**{component.Name}** ({component.NickName}) · IfcHopper > {panel}");
            text.AppendLine();
            text.AppendLine(Escape(component.Description));
            text.AppendLine();
            text.AppendLine("## Inputs");
            text.AppendLine();
            Table(text, component.Params.Input, true);
            text.AppendLine("## Outputs");
            text.AppendLine();
            Table(text, component.Params.Output, false);
            return text.ToString();
        }

        private static void Table(StringBuilder text, System.Collections.Generic.List<IGH_Param> parameters, bool inputs)
        {
            text.AppendLine(inputs ? "| Name | Type | Access | Description |" : "| Name | Type | Access | Description |");
            text.AppendLine("| --- | --- | --- | --- |");
            foreach (var param in parameters)
            {
                var name = $"**{Escape(param.Name)}** ({Escape(param.NickName)})";
                var description = Escape(param.Description);
                if (inputs)
                {
                    var value = Default(param);
                    if (value != null) description += $" Default: `{value}`.";
                    if (!param.Optional && value == null) name += " \\*";
                }
                text.AppendLine($"| {name} | {Escape(param.TypeName)} | {param.Access.ToString().ToLowerInvariant()} | {description} |");
            }
            text.AppendLine();
            if (inputs && parameters.Any(p => !p.Optional && Default(p) == null)) text.AppendLine("\\* Required.").AppendLine();
        }

        private static string ParamsPage(System.Collections.Generic.List<IGH_ObjectProxy> parameters, string panel, string iconDir, string iconUrl)
        {
            var text = new StringBuilder();
            text.AppendLine("---");
            text.AppendLine("sidebar_position: 1");
            text.AppendLine("title: Parameters");
            text.AppendLine("sidebar_label: Parameters");
            text.AppendLine("---");
            text.AppendLine();
            text.AppendLine("{/* Generated by tools/SampleBuilder --docs from the IfcHopper parameters; do not edit by hand. */}");
            text.AppendLine();
            text.AppendLine($"Parameters of the {panel} panel. They hold IfcHopper objects, e.g. to collect them or to internalise small ones (units, contexts, georeferences).");
            text.AppendLine();
            text.AppendLine("| | Name | Description |");
            text.AppendLine("| --- | --- | --- |");
            foreach (var proxy in parameters.OrderBy(p => (int)p.Exposure).ThenBy(p => p.Desc.Name))
            {
                var slug = "param-" + Slug(proxy.Desc.Name);
                proxy.Icon?.Save(Path.Combine(iconDir, slug + ".png"), ImageFormat.Png);
                var icon = proxy.Icon == null ? "" : $"![{proxy.Desc.Name}]({iconUrl}/{slug}.png)";
                text.AppendLine($"| {icon} | **{Escape(proxy.Desc.Name)}** ({Escape(proxy.Desc.NickName)}) | {Escape(proxy.Desc.Description)} |");
            }
            return text.ToString();
        }

        /// <summary>The default value of an input (its persistent data when it holds one value), or null.</summary>
        private static string Default(IGH_Param param)
        {
            if (!(param.GetType().GetProperty("PersistentData")?.GetValue(param) is IGH_Structure data) || data.DataCount != 1) return null;
            var value = data.AllData(true).FirstOrDefault()?.ToString();
            return string.IsNullOrEmpty(value) ? null : value.Replace("`", "'");
        }

        private static void WriteCategory(string dir, string label, int position, string description) =>
            File.WriteAllText(Path.Combine(dir, "_category_.json"),
                "{\n" +
                $"  \"label\": \"{label}\",\n" +
                $"  \"position\": {position},\n" +
                "  \"collapsed\": true,\n" +
                $"  \"link\": {{ \"type\": \"generated-index\", \"description\": \"{description}\" }}\n" +
                "}\n");

        /// <summary>Panel position and label from a subcategory such as "1 - File".</summary>
        private static (int, string) Panel(string subCategory)
        {
            var parts = subCategory.Split(new[] { " - " }, 2, StringSplitOptions.None);
            return parts.Length == 2 && int.TryParse(parts[0], out var position) ? (position, parts[1]) : (99, subCategory);
        }

        private static string Slug(string name) =>
            new string(name.ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray()).Trim('-').Replace("--", "-");

        /// <summary>Escapes text for a Markdown table in MDX: pipes, braces, angle brackets and line breaks.</summary>
        private static string Escape(string text) =>
            (text ?? "").Replace("\r", "").Replace("\n", " ").Replace("|", "\\|").Replace("{", "\\{").Replace("}", "\\}").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
