//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IfcHopper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IfcHopper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IfcHopper {
            get {
                object obj = ResourceManager.GetObject("IfcHopper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;64&quot;
        ///   height=&quot;64&quot;
        ///   viewBox=&quot;0 0 16.933333 16.933333&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:export-filename=&quot;ICON 1000x1000.png&quot;
        ///   inkscape:export-xdpi=&quot;1500&quot;
        ///   inkscape:export-ydpi=&quot;1500&quot;
        ///   sodipodi:docname=&quot;ICON.svg&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IfcHopper_svg {
            get {
                return ResourceManager.GetString("IfcHopper_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadIfcHeader {
            get {
                object obj = ResourceManager.GetObject("ReadIfcHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot;&gt;
        ///  &lt;!-- Read IFC Header: document with amber header band, arrow leaving the header. --&gt;
        ///  &lt;defs&gt;
        ///    &lt;linearGradient id=&quot;paper&quot; x1=&quot;0&quot; y1=&quot;0&quot; x2=&quot;1&quot; y2=&quot;1&quot;&gt;
        ///      &lt;stop offset=&quot;0&quot; stop-color=&quot;#FFFFFF&quot;/&gt;
        ///      &lt;stop offset=&quot;1&quot; stop-color=&quot;#C5C5C5&quot;/&gt;
        ///    &lt;/linearGradient&gt;
        ///    &lt;linearGradient id=&quot;fold&quot; x1=&quot;0&quot; y1=&quot;0&quot; x2=&quot;1&quot; y2=&quot;1&quot;&gt;
        ///      &lt;stop offset=&quot;0&quot; stop-color=&quot;#E0E0E0&quot;/&gt;
        ///      &lt;stop offset=&quot;1&quot; stop-color=&quot;#9A9A9A&quot;/&gt;
        ///    &lt;/l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadIfcHeader_svg {
            get {
                return ResourceManager.GetString("ReadIfcHeader_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WriteIfc {
            get {
                object obj = ResourceManager.GetObject("WriteIfc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot;&gt;
        ///  &lt;!-- Write IFC: arrow entering a document. --&gt;
        ///  &lt;defs&gt;
        ///    &lt;linearGradient id=&quot;paper&quot; x1=&quot;0&quot; y1=&quot;0&quot; x2=&quot;1&quot; y2=&quot;1&quot;&gt;
        ///      &lt;stop offset=&quot;0&quot; stop-color=&quot;#FFFFFF&quot;/&gt;
        ///      &lt;stop offset=&quot;1&quot; stop-color=&quot;#C5C5C5&quot;/&gt;
        ///    &lt;/linearGradient&gt;
        ///    &lt;linearGradient id=&quot;fold&quot; x1=&quot;0&quot; y1=&quot;0&quot; x2=&quot;1&quot; y2=&quot;1&quot;&gt;
        ///      &lt;stop offset=&quot;0&quot; stop-color=&quot;#E0E0E0&quot;/&gt;
        ///      &lt;stop offset=&quot;1&quot; stop-color=&quot;#9A9A9A&quot;/&gt;
        ///    &lt;/linearGradient&gt;
        ///    &lt;linearGradient id= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WriteIfc_svg {
            get {
                return ResourceManager.GetString("WriteIfc_svg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Project {
            get {
                object obj = ResourceManager.GetObject("Project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the Project SVG icon.
        /// </summary>
        internal static string Project_svg {
            get {
                return ResourceManager.GetString("Project_svg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Model {
            get {
                object obj = ResourceManager.GetObject("Model", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the Model SVG icon.
        /// </summary>
        internal static string Model_svg {
            get {
                return ResourceManager.GetString("Model_svg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Site {
            get {
                object obj = ResourceManager.GetObject("Site", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the Site SVG icon.
        /// </summary>
        internal static string Site_svg {
            get {
                return ResourceManager.GetString("Site_svg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Building {
            get {
                object obj = ResourceManager.GetObject("Building", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the Building SVG icon.
        /// </summary>
        internal static string Building_svg {
            get {
                return ResourceManager.GetString("Building_svg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Storey {
            get {
                object obj = ResourceManager.GetObject("Storey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the Storey SVG icon.
        /// </summary>
        internal static string Storey_svg {
            get {
                return ResourceManager.GetString("Storey_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Facility {
            get {
                object obj = ResourceManager.GetObject("Facility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Facility SVG icon.
        /// </summary>
        internal static string Facility_svg {
            get {
                return ResourceManager.GetString("Facility_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Road {
            get {
                object obj = ResourceManager.GetObject("Road", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Road SVG icon.
        /// </summary>
        internal static string Road_svg {
            get {
                return ResourceManager.GetString("Road_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bridge {
            get {
                object obj = ResourceManager.GetObject("Bridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Bridge SVG icon.
        /// </summary>
        internal static string Bridge_svg {
            get {
                return ResourceManager.GetString("Bridge_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Railway {
            get {
                object obj = ResourceManager.GetObject("Railway", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Railway SVG icon.
        /// </summary>
        internal static string Railway_svg {
            get {
                return ResourceManager.GetString("Railway_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MarineFacility {
            get {
                object obj = ResourceManager.GetObject("MarineFacility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the MarineFacility SVG icon.
        /// </summary>
        internal static string MarineFacility_svg {
            get {
                return ResourceManager.GetString("MarineFacility_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FacilityPart {
            get {
                object obj = ResourceManager.GetObject("FacilityPart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the FacilityPart SVG icon.
        /// </summary>
        internal static string FacilityPart_svg {
            get {
                return ResourceManager.GetString("FacilityPart_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RoadPart {
            get {
                object obj = ResourceManager.GetObject("RoadPart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the RoadPart SVG icon.
        /// </summary>
        internal static string RoadPart_svg {
            get {
                return ResourceManager.GetString("RoadPart_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BridgePart {
            get {
                object obj = ResourceManager.GetObject("BridgePart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the BridgePart SVG icon.
        /// </summary>
        internal static string BridgePart_svg {
            get {
                return ResourceManager.GetString("BridgePart_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RailwayPart {
            get {
                object obj = ResourceManager.GetObject("RailwayPart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the RailwayPart SVG icon.
        /// </summary>
        internal static string RailwayPart_svg {
            get {
                return ResourceManager.GetString("RailwayPart_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MarinePart {
            get {
                object obj = ResourceManager.GetObject("MarinePart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the MarinePart SVG icon.
        /// </summary>
        internal static string MarinePart_svg {
            get {
                return ResourceManager.GetString("MarinePart_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadIfc {
            get {
                object obj = ResourceManager.GetObject("ReadIfc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ReadIfc SVG icon.
        /// </summary>
        internal static string ReadIfc_svg {
            get {
                return ResourceManager.GetString("ReadIfc_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructModel {
            get {
                object obj = ResourceManager.GetObject("DeconstructModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructModel SVG icon.
        /// </summary>
        internal static string DeconstructModel_svg {
            get {
                return ResourceManager.GetString("DeconstructModel_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructProject {
            get {
                object obj = ResourceManager.GetObject("DeconstructProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructProject SVG icon.
        /// </summary>
        internal static string DeconstructProject_svg {
            get {
                return ResourceManager.GetString("DeconstructProject_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructSite {
            get {
                object obj = ResourceManager.GetObject("DeconstructSite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructSite SVG icon.
        /// </summary>
        internal static string DeconstructSite_svg {
            get {
                return ResourceManager.GetString("DeconstructSite_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructFacility {
            get {
                object obj = ResourceManager.GetObject("DeconstructFacility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructFacility SVG icon.
        /// </summary>
        internal static string DeconstructFacility_svg {
            get {
                return ResourceManager.GetString("DeconstructFacility_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructStorey {
            get {
                object obj = ResourceManager.GetObject("DeconstructStorey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructStorey SVG icon.
        /// </summary>
        internal static string DeconstructStorey_svg {
            get {
                return ResourceManager.GetString("DeconstructStorey_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructFacilityPart {
            get {
                object obj = ResourceManager.GetObject("DeconstructFacilityPart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructFacilityPart SVG icon.
        /// </summary>
        internal static string DeconstructFacilityPart_svg {
            get {
                return ResourceManager.GetString("DeconstructFacilityPart_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Context {
            get {
                object obj = ResourceManager.GetObject("Context", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Context SVG icon.
        /// </summary>
        internal static string Context_svg {
            get {
                return ResourceManager.GetString("Context_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructContext {
            get {
                object obj = ResourceManager.GetObject("DeconstructContext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructContext SVG icon.
        /// </summary>
        internal static string DeconstructContext_svg {
            get {
                return ResourceManager.GetString("DeconstructContext_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Units {
            get {
                object obj = ResourceManager.GetObject("Units", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Units SVG icon.
        /// </summary>
        internal static string Units_svg {
            get {
                return ResourceManager.GetString("Units_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructUnits {
            get {
                object obj = ResourceManager.GetObject("DeconstructUnits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructUnits SVG icon.
        /// </summary>
        internal static string DeconstructUnits_svg {
            get {
                return ResourceManager.GetString("DeconstructUnits_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Element {
            get {
                object obj = ResourceManager.GetObject("Element", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Element SVG icon.
        /// </summary>
        internal static string Element_svg {
            get {
                return ResourceManager.GetString("Element_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModelParam {
            get {
                object obj = ResourceManager.GetObject("ModelParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModelParam SVG icon.
        /// </summary>
        internal static string ModelParam_svg {
            get {
                return ResourceManager.GetString("ModelParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectParam {
            get {
                object obj = ResourceManager.GetObject("ProjectParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ProjectParam SVG icon.
        /// </summary>
        internal static string ProjectParam_svg {
            get {
                return ResourceManager.GetString("ProjectParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SiteParam {
            get {
                object obj = ResourceManager.GetObject("SiteParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the SiteParam SVG icon.
        /// </summary>
        internal static string SiteParam_svg {
            get {
                return ResourceManager.GetString("SiteParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FacilityParam {
            get {
                object obj = ResourceManager.GetObject("FacilityParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the FacilityParam SVG icon.
        /// </summary>
        internal static string FacilityParam_svg {
            get {
                return ResourceManager.GetString("FacilityParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FacilityPartParam {
            get {
                object obj = ResourceManager.GetObject("FacilityPartParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the FacilityPartParam SVG icon.
        /// </summary>
        internal static string FacilityPartParam_svg {
            get {
                return ResourceManager.GetString("FacilityPartParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StoreyParam {
            get {
                object obj = ResourceManager.GetObject("StoreyParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the StoreyParam SVG icon.
        /// </summary>
        internal static string StoreyParam_svg {
            get {
                return ResourceManager.GetString("StoreyParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ContextParam {
            get {
                object obj = ResourceManager.GetObject("ContextParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ContextParam SVG icon.
        /// </summary>
        internal static string ContextParam_svg {
            get {
                return ResourceManager.GetString("ContextParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnitsParam {
            get {
                object obj = ResourceManager.GetObject("UnitsParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the UnitsParam SVG icon.
        /// </summary>
        internal static string UnitsParam_svg {
            get {
                return ResourceManager.GetString("UnitsParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ElementParam {
            get {
                object obj = ResourceManager.GetObject("ElementParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ElementParam SVG icon.
        /// </summary>
        internal static string ElementParam_svg {
            get {
                return ResourceManager.GetString("ElementParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Georeference {
            get {
                object obj = ResourceManager.GetObject("Georeference", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Georeference SVG icon.
        /// </summary>
        internal static string Georeference_svg {
            get {
                return ResourceManager.GetString("Georeference_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructGeoreference {
            get {
                object obj = ResourceManager.GetObject("DeconstructGeoreference", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructGeoreference SVG icon.
        /// </summary>
        internal static string DeconstructGeoreference_svg {
            get {
                return ResourceManager.GetString("DeconstructGeoreference_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GeoreferenceParam {
            get {
                object obj = ResourceManager.GetObject("GeoreferenceParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the GeoreferenceParam SVG icon.
        /// </summary>
        internal static string GeoreferenceParam_svg {
            get {
                return ResourceManager.GetString("GeoreferenceParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructObject {
            get {
                object obj = ResourceManager.GetObject("DeconstructObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructObject SVG icon.
        /// </summary>
        internal static string DeconstructObject_svg {
            get {
                return ResourceManager.GetString("DeconstructObject_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyProject {
            get {
                object obj = ResourceManager.GetObject("ModifyProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifyProject SVG icon.
        /// </summary>
        internal static string ModifyProject_svg {
            get {
                return ResourceManager.GetString("ModifyProject_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifySite {
            get {
                object obj = ResourceManager.GetObject("ModifySite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifySite SVG icon.
        /// </summary>
        internal static string ModifySite_svg {
            get {
                return ResourceManager.GetString("ModifySite_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyFacility {
            get {
                object obj = ResourceManager.GetObject("ModifyFacility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifyFacility SVG icon.
        /// </summary>
        internal static string ModifyFacility_svg {
            get {
                return ResourceManager.GetString("ModifyFacility_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyStorey {
            get {
                object obj = ResourceManager.GetObject("ModifyStorey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifyStorey SVG icon.
        /// </summary>
        internal static string ModifyStorey_svg {
            get {
                return ResourceManager.GetString("ModifyStorey_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyFacilityPart {
            get {
                object obj = ResourceManager.GetObject("ModifyFacilityPart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifyFacilityPart SVG icon.
        /// </summary>
        internal static string ModifyFacilityPart_svg {
            get {
                return ResourceManager.GetString("ModifyFacilityPart_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyObject {
            get {
                object obj = ResourceManager.GetObject("ModifyObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifyObject SVG icon.
        /// </summary>
        internal static string ModifyObject_svg {
            get {
                return ResourceManager.GetString("ModifyObject_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApplyEdits {
            get {
                object obj = ResourceManager.GetObject("ApplyEdits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ApplyEdits SVG icon.
        /// </summary>
        internal static string ApplyEdits_svg {
            get {
                return ResourceManager.GetString("ApplyEdits_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Space {
            get {
                object obj = ResourceManager.GetObject("Space", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Space SVG icon.
        /// </summary>
        internal static string Space_svg {
            get {
                return ResourceManager.GetString("Space_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructSpace {
            get {
                object obj = ResourceManager.GetObject("DeconstructSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructSpace SVG icon.
        /// </summary>
        internal static string DeconstructSpace_svg {
            get {
                return ResourceManager.GetString("DeconstructSpace_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifySpace {
            get {
                object obj = ResourceManager.GetObject("ModifySpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifySpace SVG icon.
        /// </summary>
        internal static string ModifySpace_svg {
            get {
                return ResourceManager.GetString("ModifySpace_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpaceParam {
            get {
                object obj = ResourceManager.GetObject("SpaceParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the SpaceParam SVG icon.
        /// </summary>
        internal static string SpaceParam_svg {
            get {
                return ResourceManager.GetString("SpaceParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructElementType {
            get {
                object obj = ResourceManager.GetObject("DeconstructElementType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructElementType SVG icon.
        /// </summary>
        internal static string DeconstructElementType_svg {
            get {
                return ResourceManager.GetString("DeconstructElementType_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyElementType {
            get {
                object obj = ResourceManager.GetObject("ModifyElementType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the ModifyElementType SVG icon.
        /// </summary>
        internal static string ModifyElementType_svg {
            get {
                return ResourceManager.GetString("ModifyElementType_svg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ElementType {
            get {
                object obj = ResourceManager.GetObject("ElementType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the ElementType SVG icon.
        /// </summary>
        internal static string ElementType_svg {
            get {
                return ResourceManager.GetString("ElementType_svg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ElementTypeParam {
            get {
                object obj = ResourceManager.GetObject("ElementTypeParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ElementTypeParam SVG icon.
        /// </summary>
        internal static string ElementTypeParam_svg {
            get {
                return ResourceManager.GetString("ElementTypeParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Material {
            get {
                object obj = ResourceManager.GetObject("Material", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Material SVG icon.
        /// </summary>
        internal static string Material_svg {
            get {
                return ResourceManager.GetString("Material_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LayerSet {
            get {
                object obj = ResourceManager.GetObject("LayerSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the LayerSet SVG icon.
        /// </summary>
        internal static string LayerSet_svg {
            get {
                return ResourceManager.GetString("LayerSet_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConstituentSet {
            get {
                object obj = ResourceManager.GetObject("ConstituentSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ConstituentSet SVG icon.
        /// </summary>
        internal static string ConstituentSet_svg {
            get {
                return ResourceManager.GetString("ConstituentSet_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyMaterial {
            get {
                object obj = ResourceManager.GetObject("ModifyMaterial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModifyMaterial SVG icon.
        /// </summary>
        internal static string ModifyMaterial_svg {
            get {
                return ResourceManager.GetString("ModifyMaterial_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructMaterial {
            get {
                object obj = ResourceManager.GetObject("DeconstructMaterial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructMaterial SVG icon.
        /// </summary>
        internal static string DeconstructMaterial_svg {
            get {
                return ResourceManager.GetString("DeconstructMaterial_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaterialParam {
            get {
                object obj = ResourceManager.GetObject("MaterialParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the MaterialParam SVG icon.
        /// </summary>
        internal static string MaterialParam_svg {
            get {
                return ResourceManager.GetString("MaterialParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pset {
            get {
                object obj = ResourceManager.GetObject("Pset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Pset SVG icon.
        /// </summary>
        internal static string Pset_svg {
            get {
                return ResourceManager.GetString("Pset_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Qto {
            get {
                object obj = ResourceManager.GetObject("Qto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Qto SVG icon.
        /// </summary>
        internal static string Qto_svg {
            get {
                return ResourceManager.GetString("Qto_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructPset {
            get {
                object obj = ResourceManager.GetObject("DeconstructPset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructPset SVG icon.
        /// </summary>
        internal static string DeconstructPset_svg {
            get {
                return ResourceManager.GetString("DeconstructPset_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PropertySetParam {
            get {
                object obj = ResourceManager.GetObject("PropertySetParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the PropertySetParam SVG icon.
        /// </summary>
        internal static string PropertySetParam_svg {
            get {
                return ResourceManager.GetString("PropertySetParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructQto {
            get {
                object obj = ResourceManager.GetObject("DeconstructQto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructQto SVG icon.
        /// </summary>
        internal static string DeconstructQto_svg {
            get {
                return ResourceManager.GetString("DeconstructQto_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Classification {
            get {
                object obj = ResourceManager.GetObject("Classification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Classification SVG icon.
        /// </summary>
        internal static string Classification_svg {
            get {
                return ResourceManager.GetString("Classification_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeconstructClassification {
            get {
                object obj = ResourceManager.GetObject("DeconstructClassification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the DeconstructClassification SVG icon.
        /// </summary>
        internal static string DeconstructClassification_svg {
            get {
                return ResourceManager.GetString("DeconstructClassification_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClassificationParam {
            get {
                object obj = ResourceManager.GetObject("ClassificationParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ClassificationParam SVG icon.
        /// </summary>
        internal static string ClassificationParam_svg {
            get {
                return ResourceManager.GetString("ClassificationParam_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Opening {
            get {
                object obj = ResourceManager.GetObject("Opening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the Opening SVG icon.
        /// </summary>
        internal static string Opening_svg {
            get {
                return ResourceManager.GetString("Opening_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindObjects {
            get {
                object obj = ResourceManager.GetObject("FindObjects", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the FindObjects SVG icon.
        /// </summary>
        internal static string FindObjects_svg {
            get {
                return ResourceManager.GetString("FindObjects_svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModelInfo {
            get {
                object obj = ResourceManager.GetObject("ModelInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ModelInfo SVG icon.
        /// </summary>
        internal static string ModelInfo_svg {
            get {
                return ResourceManager.GetString("ModelInfo_svg", resourceCulture);
            }
        }
    }
}
