using System.Collections.Generic;
using System.IO;
using System.Linq;
using IfcHopper.Core.IO;
using IfcHopper.Core.Model;
using Xunit;

namespace IfcHopper.Tests
{
    /// <summary>The IFC files written by the sample definitions (samples/ifc, generated by tools/SampleBuilder) read back with their content.</summary>
    public class SampleDefinitionTests
    {
        private static string SampleIfc(string name) => Path.Combine(TestFiles.RepositoryRoot, "samples", "ifc", name + ".ifc");

        public static IEnumerable<object[]> Files() =>
            Directory.Exists(Path.Combine(TestFiles.RepositoryRoot, "samples", "ifc"))
                ? Directory.GetFiles(Path.Combine(TestFiles.RepositoryRoot, "samples", "ifc"), "*.ifc").Select(f => new object[] { Path.GetFileNameWithoutExtension(f) })
                : new[] { new object[] { "01 First building" } };

        [Theory]
        [MemberData(nameof(Files))]
        public void SampleFiles_AreReadWithObjects(string name)
        {
            var model = IfcBackend.Reader.Read(SampleIfc(name));
            Assert.NotNull(model.Project);
            Assert.NotEmpty(Descendants(model.Project).OfType<Element>());
        }

        [Fact]
        public void SampleFiles_HoldWhatTheirSamplesShow()
        {
            var openings = Elements("11 Openings").Single(e => e.Name == "Wall").Openings;
            Assert.Equal(3, openings.Count);
            Assert.Equal(new[] { "Door", "Window" }, openings.SelectMany(o => o.Fills).Select(f => f.Name).OrderBy(n => n));

            var chairs = Elements("07 Types and blocks").Where(e => e.Name == "Chair").ToList();
            Assert.Equal(2, chairs.Count);
            Assert.Equal(("Chair", "IfcFurnitureType"), (chairs[0].Type.Name, chairs[0].Type.IfcClass));
            Assert.NotNull(chairs[0].TypeTransform);

            var wall = Elements("10 Classification").Single();
            Assert.Equal(new[] { ("Uniclass 2015", false), ("OmniClass", true) }, wall.Classifications.Select(c => (c.System, c.FromType)));

            var edited = Elements("13 Edit in place");
            Assert.Contains(edited, e => e.Name == "South wall (renovated)" && e.PropertySets.Any(s => s.Name == "Pset_WallCommon"));
            Assert.Equal(Elements("01 First building").Select(e => e.GlobalId), edited.Select(e => e.GlobalId));
        }

        private static List<Element> Elements(string name) =>
            Descendants(IfcBackend.Reader.Read(SampleIfc(name)).Project).OfType<Element>().ToList();

        private static IEnumerable<ModelObject> Descendants(ModelObject parent) =>
            parent.Children.SelectMany(c => new[] { c }.Concat(Descendants(c)));
    }
}
